name: khdemti
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.2
  provider: ^6.1.2
  google_fonts: ^8.0.0
  flutter_animate: ^4.5.0
  intl: ^0.20.2
  shared_preferences: ^2.5.1
  shimmer: ^3.0.0
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.17
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  google_sign_in: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "Assets/logo.jpeg"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - Assets/
